### ISSUE TITLE
Feature Request: Add Github Link to Header Section

### ISSUE THREAD

**Issue by Vijaykv5** [JunDevHarsh/ReadmeEase#7] opened 2023-03-04 12:05 UTC
![Capture](https://user-images.githubusercontent.com/94985341/222900123-4878ecc1-8bc6-403c-85b8-7f8f2e930522.PNG)

Add a github icon and  link to your profile

**Comment by itsxharsh** [comment] 2023-03-04 12:12
Thank you @Vijaykv5 for raising this issue. The header section of the project is missing a link to the GitHub repository. It would be helpful to add a link to the repository to make it easier for users to access the source code.

**Comment by Vijaykv5** [comment] 2023-03-04 13:23
May you assign it to me . I can check it out

**Comment by itsxharsh** [comment] 2023-03-05 03:25
Thank you @Vijaykv5 for showing interest in contributing to this project. Just want to know about the process and what are you implementing here. Like, add a `Github` icon or something else.

**Comment by Vijaykv5** [comment] 2023-03-05 04:23
Yeah basically a github icon at the top(Header) that links to this repo

**Comment by itsxharsh** [comment] 2023-03-05 07:57
Okay, I am assigning this issue to you. Remember to update your fork with project's `dev` branch and then make a PR reference to the `dev` branch only.

**Comment by iONBain** [comment] 2023-03-21 02:38
is the issue still open ? I can work on it if not moved

**Comment by itsxharsh** [comment] 2023-03-30 02:20
Hello @iONBain, sorry for the late reply. Yes, the issue is still open. You can work on it if you want to. Reply if you want me to assign you this issue.

**Comment by iONBain** [comment] 2023-03-30 02:25
Yes, I can work on it Harsh

**Comment by itsxharsh** [comment] 2023-03-30 02:34
Thank you @iONBain for replying quickly, now you can work on it.

**Comment by iONBain** [comment] 2023-04-01 02:05
Hi @JunDevHarsh, I have opened a PR (feature: added github link in header #13) for this feat. Pls review and take necessary actions. Thanks.

**Comment by iONBain** [comment] 2023-04-01 14:35
I have opened a PR #14 for merging to dev branch as mentioned.

**Comment by itsxharsh** [comment] 2023-04-01 16:44
Thank you @iONBain for contributing to this project. Now, I am closing this issue as completed.

**Closed as completed by itsxharsh** 2023-04-01 16:44 UTC
Labels: enhancement, good first issue
